// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:suivi_quotidien/app/data/models/note.dart';
import 'package:suivi_quotidien/app/data/models/work_session.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(NoteAdapter());
    registerAdapter(WorkSessionAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(NoteAdapter());
    registerAdapter(WorkSessionAdapter());
  }
}
